//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 期中專題
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HealthReport()
        {
            this.ReportDetails = new HashSet<ReportDetail>();
            this.ReportDetails1 = new HashSet<ReportDetail>();
        }
    
        public int ReportID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public Nullable<int> PlanID { get; set; }
        public Nullable<int> ReserveID { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Plan Plan { get; set; }
        public virtual Reserve Reserve { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportDetail> ReportDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportDetail> ReportDetails1 { get; set; }
    }
}
